apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-zkg4
  namespace: marialeonova-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:marialeonova-tenant-devfile-sample-code-with-quarkus-zkg4
        name: container-image
        resources: {}
status: {}
