apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: my-app-2
    appstudio.openshift.io/component: devfile-sample-code-with-quarkus-zkg4
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-zkg4
  namespace: marialeonova-tenant
spec:
  url: https://github.com/devfile-samples/devfile-sample-code-with-quarkus
